max_width = 100
trailing_comma = "Always"
format_strings = true
brace_style = "PreferSameLine"
combine_control_expr=false
control_brace_style = "AlwaysSameLine"
empty_item_single_line=true
fn_call_width=100
fn_params_layout="Tall"
fn_single_line=true
format_code_in_doc_comments=true
indent_style="Block"